### ISSUE TITLE
Update status for tr on Transifex

### ISSUE THREAD

**Issue by caugner** [selcukkutuk/vue-cli-locale-tr#1]
Similar to `tr-tr` (https://github.com/selcukkutuk/vue-cli-locale-tr-tr/issues/1), the `tr` locale is also on Transifex: https://www.transifex.com/vuejs/vue-cli/language/tr/

Translations can be added here (currently 137 untranslated keys): https://www.transifex.com/vuejs/vue-cli/translate/#tr/$/148882921?q=translated%3Ano

Afterwards, the JSON file can be exported via the link above or directly here:
https://www.transifex.com/vuejs/vue-cli/cli-ui/tr/download/for_use/
(Note: This file contains the English key for all untranslated keys.)

**Comment by selcukkutuk** [comment]
It was very difficult to keep track of the changes. Thank you so much.
